# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.02177371432361178
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.047409463544625684
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.10322801154563672
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.22476572335891926
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.48939846501570633
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.065602236766611
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.320211868595791
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.051963039705822
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue 
