# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/COMPAS/COV_DP/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/COMPAS/COV_DP/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/COMPAS/COV_DP/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.01 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.05 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.1 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 1 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 64  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 128  --plot   -f COV_DP -fv 10.999999999999996
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.7049009242137597
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 0.9937706259148252
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.4010196653276936
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 1.975160113862287
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 2.784584379463362
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 3.9257122052698454
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 5.534476323383901
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 7.802514950784964
queue 
arguments = run.py -d COMPAS -c 0.6 -lr 0.5 -i 30 -p ../res/COMPAS/COV_DP/raw -ts 200 -e 10 -bs 1024 -nb 256  --plot   -f COV_DP -fv 10.999999999999996
queue 
