# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.20000000000000004
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.3121789588256739
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.4872785116674089
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.7605904921522783
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.1872017396640255
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.8530970150217208
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 2.892489483762224
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 4.514871777275509
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 7.047239853306441
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 10.999999999999996
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.16681005372000587
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.2782559402207124
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.46415888336127786
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.774263682681127
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.291549665014884
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 2.1544346900318834
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 3.593813663804626
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 5.994842503189409
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 10.0
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.07999999999999999
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.12665787901179792
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.2005277289470905
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.31748021039363994
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.5026421259584725
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.7957948196985137
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.2599210498948734
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.9947365987750294
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 3.158113834850661
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 5.000000000000001
queue
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 64 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 1.0
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.016681005372000592
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.027825594022071243
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.046415888336127774
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0774263682681127
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1291549665014884
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.21544346900318834
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.3593813663804626
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.5994842503189409
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 30 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 1.0
queue 
