# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6122
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/COMPAS/BD_DP/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.01 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.05 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.1 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 64 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 128 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 256 -a    -f BD_DP -fv 0.1
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.8329807108324375e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.359818286283781e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.158482110660267e-06
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 1.1288378916846883e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 2.06913808111479e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 3.792690190732254e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 6.951927961775606e-05
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00012742749857031334
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.00023357214690901214
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0004281332398719391
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0007847599703514606
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0014384498882876629
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.0026366508987303583
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.004832930238571752
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.008858667904100823
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.01623776739188721
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.029763514416313194
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.05455594781168514
queue 
arguments = run.py -d COMPAS -c 0.5 -lr 0.5 -i 10 -p ../res/COMPAS/BD_DP/raw -ts 200 -e 1 -bs 1024 -nb 512 -a    -f BD_DP -fv 0.1
queue 
