# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200
 
# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 1024
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/parameter_sweep/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/parameter_sweep/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/parameter_sweep/log/experiment.$(Process).log

# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -pid $(Process) -p ../res/parameter_sweep/FICO/raw -c 0.5 -i 30 -lr 0.5 -ts 200 -e 1 -bs 256 -nb 128 -f BD_DP -fl 0.0001 -fu 10 -fn 30
queue
arguments = run.py -d FICO -pid $(Process) -p ../res/parameter_sweep/FICO/raw -c 0.5 -i 30 -lr 0.5 -ts 200 -e 1 -bs 256 -nb 128 -f BD_EOP -fl 0.0001 -fu 10 -fn 30
queue
arguments = run.py -d FICO -pid $(Process) -p ../res/parameter_sweep/FICO/raw -c 0.5 -i 30 -lr 0.5 -ts 200 -e 1 -bs 256 -nb 128 -f COV_DP -fl 0.0001 -fu 10 -fn 30
queue
