# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200
 
# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 1024
request_cpus = 1

# ----------------------------------------------------------------------- #
# SCRIPT SELECTION                                                        #
# ----------------------------------------------------------------------- #

SelectedData = FICO

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/parameter_sweep/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/parameter_sweep/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/parameter_sweep/log/experiment.$(Process).log

# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -a -d FICO -pid $(Process)    -p ../res/parameter_sweep/FICO/raw      -c 0.5  -i 1    -lr 1   -ts 50  -e 10   -bs 500     -nb 1000 -f BD_DP -fl 0.001 -fu 10
queue 30
arguments = run.py -a -d COMPAS -pid $(Process)  -p ../res/parameter_sweep/COMPAS/raw    -c 0.5  -i 1    -lr 1   -ts 100  -e 10   -bs 250     -nb 100 -f BD_DP -fl 0.001 -fu 10
queue 30