# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200
 
# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 4096
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/parameter_sweep/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/parameter_sweep/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/parameter_sweep/log/experiment.$(Process).log

# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -a -d FICO -p ../res/parameter_sweep/FICO/raw -c 0.5 -i 30 -lr 0.01 -ts 50 -e 10 -bs 500 -nb 1000 -pid $(Process) -f BD_DP -fr 0.001 10
queue 1
