# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 4096
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/FICO/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/FICO/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/FICO/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.2
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5510813299759975
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6073812644962285
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.6694329500821695
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.7378240009220751
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.8132020634326976
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.896280949311433
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9878473951573883
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.0887685126733166
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.2
queue 
