# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 4096
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/FICO/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/FICO/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/FICO/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_DP -fv 0.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.001
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.0027825594022071257
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.004641588833612777
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.007742636826811269
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.01291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.021544346900318832
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.03593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.05994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_DP -fv 0.1
queue 
