# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/FICO/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/FICO/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/FICO/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f COV_DP -fv 3.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.020000000000000004
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.034899396208880294
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.060898392787220396
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.10626585691826114
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.1854307122033289
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.32357099472394146
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.5646216173286174
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 0.9852476765625102
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 1.7192274514116892
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/COV_DP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f COV_DP -fv 3.0
queue 
