# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 4096
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = ../res/FICO/BD_EOP/error/experiment.$(Process).err
output = ../res/FICO/BD_EOP/output/experiment.$(Process).out
log = ../res/FICO/BD_EOP/log/experiment.$(Process).log

# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.0
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.016681005372000592
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.027825594022071243
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.046415888336127774
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0774263682681127
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.1291549665014884
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.21544346900318834
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.3593813663804626
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.5994842503189409
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.0
queue 
