# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/FICO/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/FICO/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/FICO/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.01 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.05 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.1 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 1 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 128 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 256 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 64  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 128  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 256  --plot   -f BD_EOP -fv 1.1
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.01685859623784646
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.028421226711073097
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.04791419857062785
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.0807766127762215
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.13617803002551881
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.2295770424665555
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.38703466644225915
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 0.652486117159963
queue 
arguments = run.py -d FICO -c 0.5 -lr 0.5 -i 30 -p ../res/FICO/BD_EOP/raw -ts 200 -e 10 -bs 512 -nb 512  --plot   -f BD_EOP -fv 1.1
queue 
