# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200
 
# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 512
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/fkretschmar/miniconda3/envs/masters-thesis/bin/python

error = /home/fkretschmar/master-thesis/res/post_proc/error/experiment.$(Process).err
output = /home/fkretschmar/master-thesis/res/post_proc/output/experiment.$(Process).out
log = /home/fkretschmar/master-thesis/res/post_proc/log/experiment.$(Process).log

# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = post_processing.py -i ../res/FICO/raw -o ../res/FICO/processed
queue
arguments = post_processing.py -i ../res/COMPAS/raw -o ../res/COMPAS/processed
queue
arguments = post_processing.py -i ../res/ADULT/raw -o ../res/ADULT/processed
queue